export const questionVertes = [
    "Révèles ta dernière recherche internet",
"Partages une vidéo qui t'inspire, qui te fais rire",
"Partages une chanson",
"Ta qualité préférée chez les autres",
"La qualité que tu préfères chez un homme ",
"La qualité que tu préfères chez une femme",
"La qualité que tu préfères chez un/e amoureux/se",
"La qualité que tu préfères chez un/e collègue",
"Ton principal trait de caractère",
"L'adjectif qui te défini le moins",
"Ce que tu apprécies le plus chez tes amis",
"Ton principal défaut",
"Ton occupation préférée",
"Ton rêve de bonheur",
"Quel serait ton plus grand malheur ?",
"Ce que tu voudrais être",
"Ce que tu détestes par-dessus tout",
"Le don de la nature que tu voudrais avoir",
"Comment tu aimerais mourir",
"Ta devise",
"Ton état d’esprit actuel",
"En quoi tu voudrais être réincarné.e",
"Un homme ou une femme pour illustrer un nouveau billet de banque",
"Si Dieu existe, qu'aimerais-tu, après ta mort, l'entendre te dire ?",
"La chose la plus folle que tu ai faite",
"Ce que tes ami.e.s disent de toi",
"Crois-tu en l’astrologie ?",
"Une anecdote drôle / gênante",
"Tes passions",
"Un film, une chanson que tu as honte d’aimer",
"Ton plus beau voyage",
"Qu'est-ce qui te fait rire ? ",
"Aimerais-tu laisser une trace / oeuvre de toi ? Laquelle ? ",
"As-tu des manies bizarres ?",
"Montres la dernière photo de ta galerie",
"Si tu avais le choix de n’importe qui dans le monde, qui inviterais-tu à dîner ?",
"Aimerais-tu être célèbre? De quelle manière ?",
"A quoi ressemblerait une journée \"parfaite\" pour toi ?",
"Quand as-tu chanté pour toi-même pour la dernière fois ? Pour quelqu’un d’autre ?",
"Quand as-tu dansé pour toi-même pour la dernière fois ? Pour quelqu’un d’autre ?",
"Si tu pouvais vivre jusqu’à 90 ans et garder soit l’esprit soit le corps d’un trentenaire pour les 30 dernières années de ta vie, que choisirais-tu ?",
"As-tu un pressentiment sur la façon dont tu vas mourir ?",
"De quoi te sens-tu le plus reconnaissant dans ta vie ?",
"Si tu pouvais changer quelque chose dans la façon dont tu as été élevé, de quoi s’agirait-il ?",
"Si tu pouvais te réveiller demain en ayant acquis une qualité ou une compétence, laquelle serait-ce ?",
"Si une boule de cristal pouvait te révéler la vérité sur toi, ta vie, le futur ou quoi que ce soit d’autre, que voudrais-tu savoir ?",
"Y a-t-il une chose que tu rêves de faire depuis longtemps ? Pourquoi ne l’as-tu pas faite ?",
"Le plus grand accomplissement de ta vie",
"La chose la plus importante pour toi en amitié",
"Ton plus beau souvenir",
"Ton pire souvenir",
"Si tu savais que tu allais mourir soudainement dans un an, changerais-tu quelque chose à ta façon de vivre ? Que ferais-tu ?",
"Si tu gagnais 1 million d'euros au loto demain, que ferais-tu ?",
"Comment décrirais-tu ton enfance ?",
"Quand as-tu pleuré.e devant quelqu’un pour la dernière fois ? Et tout.e seul.e ?",
"De quoi ne peut-on pas rire ?",
"Ta maison, contenant tout ce qui t'appartient, prend feu. Après avoir sauvé tes proches et tes animaux de compagnie, tu as le temps d’aller récupérer en toute sécurité deux ou trois choses. Lesquelles ?",
"Parmi tous les membres de ta famille, la mort de qui te toucherais le plus ? ",
"Ta plus grosse honte",
"Ton plus grand regret, ton plus grand remord",
"Ton plus grand échec",
"Ton plus gros mensonge : à toi même, aux autres",
"Ta plus grande tristesse",
"Ta plus grande joie",
"Ton plat/aliment réconfort",
"Ta plus longue / courte expérience professionnelle ",
"Le plus beau cadeau que tes amis t’aient offert",
"Le pire cadeau que tes amis t’aient offert",
"Ton plus beau souvenir entre amis",
"La remarque la plus vexante qu’un ami t’aies faite",
"La pire chose que puisse te faire un ami",
"Les qualités indispensables pour être ton ami",
"As-tu déjà été jaloux/jalouse de ton/ta meilleur/e pote ?",
"Les meilleures vacances que tu aies passé entre amis",
"Comment réagis-tu si tu ne peux pas supporter le/la partenaire de ton/ta meilleur/e pote ?",
"Comment réagis-tu si tu apprends que le/la partenaire de ton/ta pote le/la trompe ?",
"La plus belle preuve d’amitié que l’on t’ait faite",
"Penses-tu que l’amitié entre homme et femme soit possible ?",
"Aimes-tu les grandes fêtes de famille ?",
"Comment réagirais-tu si ton enfant se droguait ?",
"Quel surnom te donne ta famille ?",
"L’amour passion dure 3 ans, es-tu d’accord ?",
"Es-tu plutôt je drague ou je me fais draguer ?",
"Comment s’est passé ta rencontre avec ton/ta partenaire ?",
"Quel est ton plus gros chagrin d’amour ?",
"Quelle est la plus belle déclaration d’amour que l’on t’ait faite ?",
"Qui t’a offert ton plus beau baiser ?",
"Es-tu plutôt gros bosseur ou moins j’en fais, mieux je me porte ?",
"As-tu déjà menti à un entretien d’embauche ou sur ton CV ?",
"Quelle est la plus grosse boulette que tu aies faite au travail ?",
"Comment vois-tu ta carrière professionnelle ?",
"Priorité à ta carrière ou ta vie privée ?",
"As-tu déjà été saoule/drogué au travail ?",
"Quel métier voulais-tu faire quand tu étais petit/e ?",
"Es-tu heureux au travail ?",
"Apprécies-tu ton/ta boss au travail ?",
"Quel patron/patronne serais-tu ?",
"T’a-t-on déjà surpris à voler ?",
"T’a-t-on déjà surpris à mentir ?",
"Quelle est la plus grosse gaffe que tu aies faite ?",
"T’es-tu déjà réveillé sans te souvenir de ta soirée ?",
"T’es-tu déjà battu ?",
"As tu déjà passé une nuit au poste de police ?",
"Quelle star adorais-tu quand tu étais ado ?",
"As-tu menti à ce jeu ?",
"Quand, avec qui et comment s'est passé ton premier bisou ?",
"As-tu un talent caché ?",
"Ton premier concert",
"Est-ce que tu fais pipi sous la douche ?",
"La chose la plus aléatoire dans ton sac en ce moment",
"Ta première voiture",
"Pourrais-tu aider un proche à cacher un cadavre sans poser de question ? ",
"L'art que tu aimerais/tu aurais aimé maîtriser",
"Ce qui t'intupportes chez les autres",
"Ce qui t'intupportes dans la vie quotidienne",
"Ce que tu voudrais être",
"La qualité que tu préfères chez un/e pote",
"Tes projets du moment",
"Combien de fois es-tu tombé.e amoureux.se ?",
"Y a-t-il une/des personnes qui te manquent particulièrement ?",
"Ton salaire net mensuel",
"Pour qui as-tu voté aux dernières élections présidentielles ?",
"Quel est le dernier message que tu ai envoyé ? ",
"As-tu déjà eu envie de frapper quelqu'un ?",
"As-tu déjà frappé quelqu'un ?",
"Le réseau social sur lequel tu passes le plus de temps ",
"Ton alcool préféré ",
"Si tu devais garder cinq fonctionnalités sur ton téléphone ",
"Trois choses que tu amènes sur un île déserte ",
"Tu te vois où et comment dans 5 ans ?",
"Tu te vois où et comment dans 15 ans ?",
"Classes ces piliers par degré d'importance pour toi : Amis, Amour, Famille, Travail",
"Un élément du quotidien qui te semble indispensable ",
"Un moment que tu affectionnes particulièrement ",
"Ton plaisir du quotidien",
"Avais tu de l'argent de poche ? ",
"Un adjectif pour te décrire quand tu étais enfant : en famille et à l'école ",
"Quel conseil donnerais tu à toi même quand tu avais 10 ans ?",
"Quel conseil donnerais tu à toi même quand tu avais 20 ans ?",
"Quel est la pire chose que l'on puisse te faire ? ",
"Assimiles à un aliment la personne se trouvant sur ta droite",
"Ton prochain tatouage "]

export const questionRouges = [
    "Comment définirais-tu les concepts suivants : couple, sexfriend, plan cul, coup d'un soir",
    "As-tu déjà été attiré(e) par une personne du même sexe ? ",
"Est ce que tu coucherais avec quelqu'un qui a des valeurs opposées aux tiennes ? ",
"As-tu déjà eu des relations sexuelles avec un(e) ami(e) de ton/ta partenaire ?",
"As-tu déjà eu des relations sexuelles avec le/la partenaire d'un(e) ami(e) ?",
"Combien de personnes as-tu aimé ?",
"As-tu déjà eu des relations sexuelles sans utiliser de moyen de contraception ?",
"As-tu déjà eu des relations sexuelles avec quelqu'un qui était engagé dans une relation avec une autre personne ? ",
"As-tu déjà eu des relations sexuelles non protégées (sans préservatif) ?",
"As-tu déjà eu des relations sexuelles avec plus d'une personne de la même famille ? ",
"As-tu déjà eu une IST ?",
"As-tu déjà posé un lapin à quelqu'un ?",
"As-tu déjà eu des relations sexuelles juste pour gagner un pari ? ",
"As-tu déjà été infidèle ? ",
"As-tu déjà eu des relations sexuelles que tu regrettes maintenant ? ",
"As-tu déjà eu des relations sexuelles avec plus de 2 personnes dans une même semaine ?  ",
"As-tu déjà acheté quelque chose dans un sex-shop ? ",
"Ta plus longue / courte relation amoureuse ",
"Les pires tue-l’amour selon toi ",
"Ce que tu regardes en premier chez une fille ou un garçon",
"Penses-tu être jaloux.se ?",
"As-tu un style d'homme ou de femme particulier ? ",
"Crois-tu au coup de foudre ?",
"Ce que tu détestes dans les premières dates",
"Ce qui te fait craquer / tomber amoureux/se d’une fille ou d’un mec ",
"Combien de relations sérieuses as-tu eues ?",
"La chose la plus dingue que tu aies faite par amour",
"Comment t’habillerais-tu pour une soirée romantique ?",
"Est-ce que tu aimes surprendre ton ou ta partenaire dans la vie de tous les jours ? ",
"Trois éléments qui te paraissent indispensables dans un couple ",
"Trois éléments qui t'insupportent dans un couple ",
"Perds-tu facilement tes moyens devant quelqu'un qui te plaît ?  ",
"Fais-tu facilement confiance ?",
"Est-ce que tu te vois vivre : célibataire, en couple (vie commune / séparée), en trouple,  autre forme ?",
"La pire excuse que tu aies donnée pour t'extirper d'un date",
"Ce qui te plaît le plus chez l'autre",
"À ton avis, ce qui a plu à l'autre chez toi",
"La première impression que tu as eu de l'autre",
"Si demain, on devait partir en week-end/vacances, ce serait où ?",
"Les points communs que je penses avoir avec l'autre",
"Les grandes différences que je penses avoir avec l'autre",
"Qui te connait le mieux ?",
"As-tu déjà eu un rapport sexuel en échange d'argent ou de drogue ? ",
"As-tu déjà été voir un.e psychologue ? Aimerais-tu ?",
"As-tu déjà été voir un.e sexothérapeute ? Aimerais-tu ?",
"As-tu déjà fantasmé sur un/une de tes potes ?",
"As-tu déjà couché avec un/une pote ?",
"As-tu déjà fantasmé sur un membre de ta famille ?",
"Si ton/ta partenaire te trompe, tu préfères qu’il/elle te l’avoue ?",
"Qu’est-ce qui est rédhibitoire chez une fille/un mec pour toi ?",
"Crois-tu à la fidélité ?",
"As-tu déjà fouillé dans le portable de ton/ta partenaire ?",
"A quel moment on passe au stade de la tromperie selon toi ?",
"As-tu déjà trompé ton/ta partenaire ?",
"As-tu déjà menti en disant je t'aime ?",
"As-tu déjà remis en question ton orientation sexuelle ?",
"L'amour sans le sexe, c'est possible ?",
"Crois-tu en l'amour pour toujours ?",
"A qui penses-tu ne pas montrer assez d'affection ?",
"Est-ce que tu t'attaches/te détaches facilement ? ",
"Désires-tu te marier ?",
"Désires-tu avoir des enfants ?",
"Pourrais-tu recoucher avec un.e ex ?",
"Quand est-ce que tu te sens vraiment toi-même ?",
"Une anecdote de date drôle / gênante",
"As-tu déjà eu envie de tuer quelqu'un ?",
"Plutôt ta mère qui trompe ton père ou ton père qui trompes ta mère ? ",
"La réaction de ta famille si tu es / ta partenaire était enceinte ?",
"Racontes la dernière fois où tu as été jaloux/se ",
"As-tu déjà eu une relation qui a commencé sur internet ? ",
"T'es t-il déjà arrivé que quelqu'un soit amoureux/amoureuse de toi sans que ce soit réciproque ? Qu'as-tu fait ? ",
"As-tu déjà eu un chagrin d'amour ? Comment t'en es-tu sorti ?",
"Es-tu pote avec tes ex ? ",
"Quelle façon de flirter ou de draguer te refroidit carrément ?"]

export const questionJaunes = [
    "Te considères-tu riche ou pauvre ? ",
"Ta proximité, ton attachement par rapport à ta famille",
"Ta situation affective",
"Ton inspiration",
"Ta patience",
"Ton exposition sur les réseaux sociaux ",
"Ta beauté physique",
"L'importance du travail",
"Ton niveau en réseaux sociaux",
"La liberté",
"Ton niveau en people",
"Ton niveau en littérature",
"L'importance du lieu de vie",
"Le bricolage",
"La / ta richesse",
"Ta santé physique",
"Ta créativité",
"La paresse",
"L'organisation",
"Le travail",
"Le café",
"Le jardinage",
"Ta situation professionnelle",
"Ton empathie envers la nature",
"Ton empathie envers les animaux",
"Ton empathie envers les gens",
"L'aventure",
"La colère",
"La curiosité",
"L'importance des amis",
"La danse",
"Le chant",
"Le stress",
"La luxure",
"Les nouvelles technologies",
"L'anxiété",
"La politique",
"L'égalité",
"L'envie",
"Ton niveau en français",
"Ton niveau en langues étrangères",
"L'orgueil",
"Ton niveau en maths",
"Ta santé psychologique",
"Ton niveau moyen d'énergie",
"Ton attachement envers les objets",
"La religion",
"La mémoire",
"L'humour",
"Ta beauté intérieure",
"L'espoir",
"Les jeux vidéos",
"Le sport",
"Le cinéma / les films",
"La cuisine",
"La musique",
"Les collègues de travail",
"L'éloquence",
"L'improvisation",
"La fraternité",
"Les jeux de société",
"L'art",
"Le romantisme",
"Le regard des autres",
"La méchanceté",
"L'avidité",
"L'égoïsme",
"Le machiavélisme",
"Le narcissisme",
"La psychopathie",
"Le sadisme",
"L'égocentrisme",
"Ta vulgarité "]

export const questionOranges = [
    "Un pays pour voyager",
"Un pays pour résider",
"Une couleur",
"Une fleur, plante, arbre",
"Un oiseau",
"Un auteur",
"Un poète",
"Un héros dans la fiction",
"Une héroïne dans la fiction",
"Un chanteur / groupe de musique",
"Un peintre",
"Un héros dans la vie réelle (vivants ou décédés)",
"Une héroïnes préférées dans la vie réelle (vivantes ou décédées)",
"Un acteur",
"Une actrice",
"Un prénom (féminin/ masculin/non genrés)",
"Un personnage historique admirable / méprisable",
"Un personnage politique",
"Un fait historique admirable / méprisable",
"Une réforme, évolution historique admirable / méprisable",
"Une expression",
"La faute qui t’inspire le plus/moins d’indulgence",
"Un plat ",
"Une boisson",
"Un son/ le bruit ",
"Un mot ",
"Une drogue",
"Un juron, gros mot ou blasphème",
"Un secteur d'activité (travail)",
"Un métier ",
"Un temps météo ",
"Un objet du quotidien ",
"Un nombre",
"Un artiste",
"Des souvenirs d'enfance",
"Une position de yoga",
"Un sport ",
"Un instrument de musique",
"Un emoji",
"Un jeu",
"Une citation / un mantra",
"Les mots",
"Une chanson / mélodie",
"Un conte / une fable",
"Une odeur",
"Un son / un bruit",
"Un animal",
"Un dessin animé",
"Cuisines du monde ",
"En voiture"]

export const questionBleues = [
    "Plutôt Netflix & Chill ou grosse soirée ?",
    "Vivre le début ou la fin du monde ?",
    "Avoir plus d’argent ou plus de temps ?",
    "Vivre sans dents ou sans yeux ?",
    "Vivre sans jambes ou sans bras ?",
    "Perdre la vue ou tes souvenirs ?",
    "Passager ou chauffeur ?",
    "Passer un an à la guerre ou un an en prison ?",
    "Résoudre la faim dans le monde ou le réchauffement climatique ?",
    "Avoir un troisième mamelon ou un orteil supplémentaire ?",
    "Trouver ton âme sœur ou ta vocation ?",
    "Etre bloqué dans la jungle ou dans le désert ?",
    "Etre invisible ou pouvoir voler ?",
    "Tomber en public ou passer des gaz en public ?",
    "Vivre dans une cabane dans les arbres ou dans une grotte ?",
    "Thé ou café ?",
    "Voir le futur ou changer le passé ?",
    "Netflix ou Arte ?",
    "Chien ou chat ?",
    "Bière ou vin ?",
    "Crêpes ou gauffres ?",
    "Perdre ton téléphone ou ton passeport ?",
    "Parler aux animaux ou parler 10 langues étrangères ?",
    "Une seconde chance en amour ou une seconde chance pour ta carrière ?",
    "Voler ou lire dans les pensées ?",
    "Mourir avant ou après tes proches ?",
    "Vivre sans films ou vivre sans musique ?",
    "Vacances à la mer ou en montagne ?",
    "Pour ou contre l'euthanasie ? ",
    "Hiver ou été ?",
    "Raclette ou fondue ? ",
    "Pâtes bolo ou pâtes carbo ? ",
    "Bière ou vin ? ",
    "Viande ou poisson ? ",
    "Coca ou spirte ? ",
    "Noël ou nouvel an ? ",
    "Être un légume ou mourir ? ",
    "Plutôt passager ou conducteur ? ",
    "Sport collectif ou individuel ?",
    "Jeu de ballon ou jeu de raquette ? ",
    "Plutôt décision réfléchie ou spontanée ? ",
    "Plutôt vacances organisées ou improvisées ?",
    "Plutôt vin rouge ou vin blanc ?",
    "As-tu déjà été bourré en famille ?"
]

export const questionNoires = [
    "En principe, tout le monde vaut la même chose",
"Il n’est pas acceptable de répandre des rumeurs, même pour défendre les personnes que l’on aime.",
"Je ne cherche pas le pouvoir.",
"La plupart des gens sont essentiellement bons et gentils.",
"Lorsque je suis énervé(e), tourmenter les autres m’aide à me sentir mieux.",
"Je pense que mentir est nécessaire afin de maintenir un avantage concurrentiel sur les autres.",
"J’aimerais faire souffrir certaines personnes, même si cela signifiait que j’irais en enfer avec elles.",
"Je ne peux pas imaginer comment être méchant envers les autres peut être excitant.",
"Je ne suis pas très compatissant(e) avec les autres ou leurs problèmes.",
"Une personne devrait obéir à la loi, peu importe à quel point cela interfère avec son ambition personnelle.",
"Je n’apprécie pas particulièrement de manipuler les sentiments des autres.",
"Si je m’opposais à l’élection d’un(e) officiel(le), alors je serais ravi de le/la voir échouer, même si son échec nuit à ma communauté.",
"Je suis prêt(e) à faire du bénévolat pour ceux qui sont dans le besoin.",
"Je déteste voir les gens souffrir.",
"Il est acceptable de réserver un mauvais traitement à quelqu’un qui se comporte comme une ordure.",
"Tout ce qui importe est mon plaisir personnel.",
"Faire du mal aux autres me mettrait très mal à l’aise.",
"J’ai tendance à pardonner les torts que j’ai subis.",
"Désormais, pour gagner de l’argent, il n’y a plus de bonnes ou de mauvaises manières. Seulement des manières simples ou fastidieuses.",
"Je serais prêt(e) à recevoir un coup de poing si cela signifiait qu’une personne que je n’aime pas en recevrait deux.",
"Peu importe combien j’ai, je ne suis jamais complètement satisfait(e).",
"S’attribuer le mérite pour les idées d’un autre, c’est hors de question.",
"Je me fiche bien d’avoir le contrôle sur les autres.",
"Il est sage de garder une trace des informations que l’on peut utiliser ultérieurement contre autrui.",
"Si mon voisin venait à se plaindre du volume trop élevé de ma musique, je le baisserais, même si cela m’embête.",
"Peu importe combien j’ai de quelque chose, je veux toujours plus.",
"Les personnes qui me cherchent finissent toujours par le regretter.",
"J’essaie avant tout de penser à moi en premier, même si cela implique de rendre les choses plus difficiles pour les autres.",
"Cela vaut parfois la peine de souffrir un peu pour aider ceux qui sont dans le besoin.",
"La revanche n’apporte que peu de réconfort.",
"Cela ne me procure pas beaucoup de plaisir de voir mes rivaux échouer.",
"Il m’est difficile de voir quelqu’un souffrir.",
"Une personne intelligente sait toujours quand, comment, et à qui se référer pour sceller le sort de la personne qui l’a offensée.",
"Les histoires d’honnêteté et de bonté servent uniquement à rendre les gens confus et stupides.",
"Si un raccourci vers le succès est illégal, alors il n’est pas malin de le prendre.",
"Les choses ne peuvent pas toujours aller dans mon sens.",
"Je ne poursuivrais pas ce que je veux si cela devait créer des problèmes à d’autres personnes.",
"Cela ne me dérange pas de partager le devant de la scène.",
"Je suis désolé si les choses que je fais contrarient les autres.",
"Une personne qui me blesse ne peut pas compter sur ma sympathie.",
"Je ne veux pas que les gens aient peur de moi ou de mes coups de tête.",
"Faire de bonnes actions donne du baume au coeur.",
"Je pense à harceler les autres pour le plaisir.",
"La plupart des gens méritent le respect.",
"En fait, je suis plutôt cupide.",
"Si jamais je tourmentais autrui, je ressentirais beaucoup de remords.",
"La plupart des gens sont des ratés, d’une manière ou d’une autre.",
"Si j’étais sur le Titanic, je ne mériterais pas de monter à bord du premier canot de sauvetage plus que quelqu’un d’autre.",
"Il y a eu des moments durant lesquels j’étais prêt(e) à endurer une petite souffrance afin de pouvoir punir quelqu’un d’autre qui le méritait.",
"Dans l’ensemble, il vaut mieux être humble et honnête plutôt qu’important et malhonnête.",
"Assurez-vous que vos projets vous avantagent vous et non les autres.",
"Faire de bonnes actions ne sert à rien; cela rend simplement les gens pauvres et paresseux .",
"Une vengeance doit être rapide et méchante.",
"J’évite d’humilier les autres.",
"Il est difficile d’aller de l’avant sans contourner quelques règles ici et là.",
"Jamais je ne tricherais, même si les chances de se faire prendre étaient minces.",
"Les personnes qui se font maltraiter ont généralement fait quelque chose pour mériter ce qui leur arrive.",
"Je dirais n’importe quoi pour obtenir ce que je veux.",
"Je peux à peine supporter le fait qu’une autre personne soit au centre de l’attention.",
"Pourquoi devrais-je me soucier des autres quand personne ne se soucie de moi?",
"Faire en sorte que les autres se sentent mal vis-à-vis d’eux-mêmes ne me fait pas me sentir mieux.",
"Pour la plupart des choses, il y a un moment où l’on peut en avoir assez et se satisfaire de ce que l’on possède.",
"Si j’ en avais l’occasion, je paierais volontiers une petite somme d’argent pour voir un(e) camarade de classe que je n’apprécie pas échouer à son examen final.",
"Ne révèlez jamais à personne la véritable raison pour laquelle vous faîtes quelque chose à moins que cela soit utile.",
"Si une entreprise fait une erreur de facturation en votre faveur, il est acceptable de ne rien dire car c’est de leur faute.",
"Je ne mérite pas plus de choses que les autres dans la vie.",
"Le succès est basé sur la survie des plus aptes; je ne m’inquiète pas des raté(e)s.",
"Je m’efforce de ne pas blesser les autres dans la poursuite des mes objectifs.",
"En établissant les priorités, nous devons tenir compte de tous les groupes.",
"Nous ne devrions pas promouvoir l’égalité entre les groupes.",
"L’égalité entre groupes devrait être notre idéal.",
"Les groupes supérieurs devraient dominer les groupes inférieurs.",
"Les fauteurs de troubles doivent ressentir sans équivoque les conséquences du fait qu’ils sont indésirables dans la société.",
"On devrait laisser les décisions importantes aux responsables/aux dirigeants.",
"Les comportements établis ne doivent pas être remis en question.",
"Tu te fais régulièrement de nouveaux amis. ",
"Tu passes une grande partie de ton temps libre à explorer divers sujets qui t'intéressent",
"Voir d'autres personnes pleurer peut facilement te donner envie de pleurer à ton tour.",
"Tu prévois souvent un plan B et un plan C. ",
"Tu restes généralement calme, même sous une forte pression. ",
"Lors d'événements sociaux, tu essayes rarement de te présenter à de nouvelles personnes et tu t'adressez plutôt à celles que tu connais déjà. ",
"Tu préfères terminer complètement un projet avant d'en commencer un autre.",
"Tu es très sentimental. ",
"Tu aimes utiliser des outils d'organisation comme les calendriers et les listes. ",
"Même une petite erreur peut te faire douter de tes capacités et de tes connaissances. ",
"Tu te sens à l'aise d'aller vers quelqu'un que tu trouves intéressant et d'entamer une conversation. ",
"Tu n'es pas très intéressé(e) par les discussions sur les différentes interprétations et analyses d'œuvres créatives. ",
"Tu as plus enclin à suivre ta raison que ton cœur.",
"Tu préfères généralement faire ce dont tu as envie à un moment donné plutôt que de planifier une routine quotidienne particulière. ",
"Tu te soucies rarement de faire bonne impression auprès des gens que tu rencontres. ",
"Tu aimes participer à des activités de groupe. ",
"Tu aimes les livres et les films dont la fin t'oblige à trouver ta propre interprétation.",
"Tu es plus heureux en aidant les autres à accomplir des choses qu'en accomplissant tes propres réalisations. ",
"Tu t'intéresses à tant de choses qu'il t'est difficile d'en choisir une. ",
"Tu as tendance à t'inquiéter que les choses se dégradent. ",
"Tu évites les rôles de leader dans les groupes. ",
"Tu n'es certainement pas un artiste. ",
"Tu penses que le monde serait meilleur si les gens se fiaient davantage à la rationalité et moins à leurs sentiments. ",
"Tu préfères accomplir tes tâches avant de te détendre. ",
"Tu aimes regarder les gens se disputer. ",
"Tu as tendance à éviter d'attirer l'attention sur toi. ",
"Ton humeur peut changer très rapidement. ",
"Tu perds patience avec les personnes qui ne sont pas aussi efficaces que toi. ",
"Tu te retrouves souvent à faire les choses au dernier moment. ",
"Tu as toujours été fasciné(e) par la question de savoir ce qui se passe après la mort. ",
"Tu préfères généralement être entouré d'autres personnes plutôt que d'être seul. ",
"Tu t'ennuies ou perds tout intérêt lorsque la discussion devient très théorique. ",
"Tu trouves facile d'éprouver de l'empathie pour une personne dont les expériences sont très différentes des tiennes. ",
"Tu reportes généralement tes décisions aussi longtemps que possible. ",
"Tu remets rarement en question les choix que tu as faits. ",
"Après une semaine longue et épuisante, un moment social animé est exactement ce dont tu as besoin.",
"Tu aimes aller dans les musées d'art. ",
"Tu as souvent du mal à comprendre les sentiments des autres. ",
"Tu aimes avoir une liste de choses à faire chaque jour. ",
"Tu manques rarement de confiance en toi.",
"Tu évites de téléphoner. ",
"Tu passes souvent beaucoup de temps à essayer de comprendre des opinions très différentes des tiennes. ",
"Dans ton cercle social, c'est souvent toi qui prend contact avec tes amis et qui initie les activités. ",
"Si tes projets sont interrompus, ta priorité est de les reprendre au plus vite. ",
"Tu es encore gêné par des erreurs que tu as commises il y a longtemps. ",
"Tu t'interroges rarement sur les raisons de l'existence humaine ou sur le sens de la vie. ",
"Tes émotions te contrôlent plus que tu ne les contrôles. ",
"Tu fais très attention à ne pas nuire à l'image des autres, même lorsque c'est entièrement leur faute. ",
"Ton style de travail personnel se rapproche plus d'explosions d'énergie spontanées que d'efforts organisés et cohérents. ",
"Lorsque quelqu'un a une haute opinion de toi, tu te demandes combien de temps il te faudra pour le décevoir. ",
"Tu adorerais avoir un travail qui t'oblige à travailler seul(e) la plupart du temps. ",
"Tu penses que réfléchir à des questions philosophiques abstraites est une perte de temps. ",
"Tu te sens plus attiré(e) par les lieux à l'atmosphère animée que par les lieux calmes et intimes. ",
"Tu sais au premier coup d'œil ce que ressent quelqu'un. ",
"Tu te sens souvent submergé(e). ",
"Tu termines les choses méthodiquement sans sauter d'étapes. ",
"Tu es très intrigué(e) par les questions jugées polémiques. ",
"Tu laisserais passer une bonne occasion si tu pensais que quelqu'un d'autre en avait plus besoin. ",
"Tu as du mal à respecter les délais. ",
"Tu es confiant dans le fait que les choses vont s'arranger pour toi. ",
"La décision la plus courageuse que vous prenez chaque jour, c’est celle d’être de bonne humeur !",
"Mieux vaut une amère vérité qu’un doux mensonge ",
"On dit que le monde appartient à ceux qui se lèvent tôt. Ce n’est pas vrai. Le monde appartient à ceux qui sont heureux de se lever. ",
"You are what you read.  ",
"L’amour du pouvoir n’est rien face au pouvoir de l’amour.  ",
"La vie c’est pas comme on veut, c’est comme on peut.",
"C’est bien la pire folie que de vouloir être sage dans un monde de fou",
"Ne demandes jamais ton chemin à qqun qui le connait, tu risquerais de ne pas te perdre ",
"Tous les changements, même les plus souhaités, ont leur part de mélancolie. Car ce que nous quittons, c’est une partie de nous-même; il faut mourir à une vie pour entrer dans une autre.  ",
"L’humour, c’est la vaseline de la pensée. ",
"La richesse, c’est comme le fumier : elle pue quand on l’entasse, mais porte de nombreux fruits quand on la répand !  ",
"Le courage n’est pas de dire ce que l’on pense, mais d’être ce que l’on dit",
"La vie, c’est ce qui vous arrive alors que vous étiez en train de prévoir autre chose. ",
"Occupés par leur désir d’atteindre la lune, les hommes ont échoué à voir les fleurs qui s’épanouissent à leurs pieds. ",
"Le plus grand échec est de ne pas avoir le courage d'oser",
"Sois le changement que tu désires voir en ce monde",
"Je me sens bien dans ma peau, elle est juste à ma taille​ ! ",
"Ils peuvent couper toutes les fleurs, mais ils ne peuvent pas arrêter le printemps",
"Nous souhaitons la vérité, et nous ne trouvons en nous qu'incertitude",
"On ne peut pas construire un monde différent avec des gens indifférents",
"Ignorer l'autre conduit à ce jour fatal où l'autre devient soi-même",
"Avoir peur du changement, c'est ignorer ses capacités",
"Je réussirai car je suis assez fou pour croire que j'y arriverai",
"L'intégrité ne souffre d'aucun compromis, d'aucune manipulation, d'aucune soumission. Elle est ou elle n'est pas.",
"Lorsque nous mettons des mots sur les maux, les dits maux deviennent des maux dits et cessent d'être maudits",
"Travailler moins pour vivre plus",
"Les gens qu'on aime, on ne les rencontre pas, on les reconnaît",
"Les émotions non exprimées ne meurent jamais. Elles sont enterrées vivantes et libérées plus tard de façon plus laide",
"Il existe deux façons d'être riche : avoir beaucoup d'argent ou avoir peu de besoins",
"Tout acte est égoïste",
"Vivons d'imprévus, c'est moins long à organiser",
]

export const questionPourpres = [
    "As-tu déjà eu des expériences sado-masochistes ou pratiqué le bondage ? Aimerais-tu ?",
"As-tu déjà utilisé des sex-toys ? Aimerais-tu ?",
"As-tu déjà pris une douche/un bain avec une personne du sexe opposé ? ",
"As-tu déjà fantasmé sur un personnage de dessin animé ? ",
"T'es tu déjà masturbé.e au travail ?",
"As-tu déjà eu des rapports avec une personne du même sexe ? Aimerais-tu ?",
"As-tu déjà été responsable de la perte de la virginité de quelqu'un ? Aimerais-tu ?",
"As-tu déjà eu des relations sexuelles avec plusieurs personnes en même temps ? Aimerais-tu ?",
"As-tu déjà eu un rapport anal ? Aimerais-tu ?",
"As-tu déjà pratiqué le voyeurisme ? Aimerais-tu ?",
"As-tu déjà eu des relations sexuelles dans un lieu public ? Aimerais-tu ?",
"Une/des pratiques sexuelles préférées ? ",
"Une/des positions préférées ? ",
"Couches-tu le premier soir ?",
"As-tu déjà reçu des messages coquins ?",
"As tu déjà couché avec une collègue ?",
"As-tu déjà fait l’amour sur ton lieu de travail ?",
"As-tu déjà couché avec ton/ta boss ?",
"As-tu déjà surpris en train de te toucher ?",
"As-tu déjà fantasmé sur un/une de tes professeurs ?",
"Aimerais-tu essayer des nouveaux trucs au lit ?",
"As-tu un désir sexuel dont tu n'as jamais parlé ?",
"Est-ce que tu ferais un strip-tease ?",
"Quel est le dernier type de porno que tu ai regardé ?",
"Aimerais-tu regardé du porno avec ton/ta partenaire ?",
"Quelle partie de ton corps trouves-tu la plus/moins séduisante ? ",
"As-tu déjà simulé l'orgasme ? ",
"As-tu déjà téléphoné / répondu à un appel pendant un acte sexuel ?",
"Plutôt coup d'un soir ou de plusieurs soirs ?",
"As-tu déjà fantasmé sur un membre de ta famille ? ",
"As-tu déjà envoyé des nudes ?",
"As-tu déjà fantasmé sur un acteur/une actrice ? ",
"As-tu déjà reçu des nudes ?",
"Plutôt dominant ou dominé ? ",
"Tu préfères prendre ou laisser les décisions ?",
"Le sexe avec ou sans musique ? ",
"Le sexe avec ou sans sons / bruits ? ",
"Après le sexe : plutôt seul ou plutôt ensemble ? ",
"Debrief après le sexe ou pas ? ",
"As-tu déjà fait des jeux de rôle sexuels ? Aimerais-tu ?",
"As-tu déjà pratiqué le sexe les yeux bandés ? Aimerais-tu ? ",
"Est ce que tu aimes souvent expérimenter de nouvelles pratiques sexuelles ? ",
"C'était quand ta première fois ? ",
"Pour ou contre la prostitution ?",
"As-tu déjà été voir un professionnel du sexe ?",
"Quelle est pour toi la condition primordiale pour faire l'amour avec quelqu'un ?",
"As-tu déjà embrassé quelqu'un du même sexe ? Est-ce que ça t'a excité(e) ? ",
"As-tu déjà fait l'amour sans en avoir envie ? Si oui, pourquoi l'as-tu fait quand même ? ",
"Par quoi es-tu rapidement excité(e) ?",
"As-tu déjà expérimenté le préservatif féminin ? ",
"Le sexe, ce n'est réussi que si les deux partenaires ont eu un orgasme. Qu'en penses-tu ? ",
"As-tu eu une éducation sexuelle ? Par qui et qu'est-ce que cela t'a apporté ? ",
"Combien de fois par jour penses-tu au sexe ?",
"Quel conseil donnerais-tu pour un beau rendez-vous érotique ?",
"Est-ce que tu parles facilement de tes souhaits et de tes limites dans le domaine sexuel ? ",
"Combien de fois par semaine te masturbes tu en moyenne ?",
"Es-tu excité(e) par certains mots ou certaines phrases cochonnes ? Est-ce que ce sont les mots qui t'excitent ou la façon dont ils sont dits ?",
"As-tu un fantasme dont tu as as un peu honte ? ",
"Pour toi, est-ce qu'un trio est un fantasme excitant ? Penses-tu qu'il se réalisera un jour ?",
"Qu'est-ce que tu trouves le plus sexy chez la personne en face de toi ? ",
"Préfères-tu un partenaire sexuel expérimenté ou justement pas ? ",
"D'après toi, comment faut-il faire pour te séduire vite ?",
"Combien de temps faut-il que tu connaisses quelqu'un avant de coucher avec cette personne ?",
"Penses-tu qu'en s'embrassant on voit si l'on va ensemble ou pas ?",
"As-tu (eu) un plan cul ?",
"As-tu (eu) un sexfriend ?",
"L'exclusivité est-elle un élément essentiel du couple ? ",
"Quand tu fais l'amour, veux-tu absolument avoir un orgasme ? ",
"T'arrive-t-il de regarder un film érotique ou du porno ? ",
"A qui peux-tu t'adresser si tu as des questions sur le sexe ?",
"As-tu déjà fait l'amour dans un endroit inhabituel ? Aimerais-tu ?",
]
