export const questionVertes = [
    "La qualité que je préfère chez un.e amoureux.se",
    "L'adjectif qui me définit le moins",
    "Mon état d'esprit actuel",
    "La faute qui m'inspire le plus d'indulgence",
    "Ce qui m'insupporte chez les autres",
    "Ma devise",
    "Ma drogue favorite",
    "La qualité que je préfère chez un.e collègue",
    "L'art que j'aimerais maîtriser",
    "L'art que j'aurais aimé maîtriser",
    "Ce que je voudrais être",
    "Le pays où je désirerais vivre",
    "Une personne pour illustrer un nouveau billet de banque",
    "La qualité que je préfère chez un.e pote",
    "Mon plus grand malheur",
    "Mon principal trait de caractère",
    "Mon principal défaut",
    "Le don de la nature que j'aimerais avoir",
    "Comment j'aimerais mourir",
    "Mes projets du moment",
    "Ce qui m'insupporte dans la vie et dans le quotidien",
    "Mon rêve de bonheur"]
export const questionRouges = [
    "Ta/tes pratiques sexuelles préférés",
    "Ta/tes positions sexuelles préférées",
    "Un secret que tu n'as dit à (presque) personne",
    "Ta plus grosse honte",
    "Ton plus grand remord/regret",
    "Ton plus grand échec",
    "Ton plus grand mensonge à toi même/ aux autres",
    "Ta plus grande tristesse",
    "Ta plus grande joie",
    "Combien de fois es-tu tombé.e amoureux ?",
    "Combien de personnes as-tu aimé ?",
    "As-tu déjà été attiré.e par une personne de même sexe ?",
    "Est-ce-que tu coucherais avec quelqu'un qui a des valeurs opposées aux tiennes ?",
    "Donne ta définition de couple/sexfriend/plan cul/coup d'un soir",
    "As-tu déjà eu des expériences sado-masochistes ou pratiqué le bondage ?",
    "As-tu déjà eu des raports avec une personne de même sexe que toi ?",
    "T'es tu déjà masturbé.e au travail ?",
    "As-tu déjà fantasmé sur des personnages de dessins animés ?",
    "As-tu déja fantasmé sur un.e collègue ?",
    "As-tu déja pris un bain ou une douche avec un membre du sexe opposé ?",
    "As-tu déjà utilisé des sextoys ?",
    "As-tu déjà eu des relations sexuelles avec un.e ami.e de ton partenaire ?",
    "As-tu déjà eu des relations sexuelles avec quelqu'un qui était engagé dans une relation avec quelqu'un d'autre ?",
    "As-tu déjà eu des relations sexuelles sans utiliser de préservatifs ?",
    "As-tu déjà eu des relations sexuelles avec plus d'une personne de la même famille ?",
    "As-tu déjà eu des relations sexuelles sans utiliser de moyen de contraception ?",
    "As-tu déjà eu une IST ?",
    "As-tu déjà été responsable de la perte de la virginité de quelqu'un ? Si oui, combien ? ",
    "As-tu déjà posé un lapin à quelqu'un ?",
    "As-tu déjà eu des raltions sexuelles juste pour gagner un pari ?",
    "As-tu déjà eu des relations sexuelles avec plusieurs personnes en même temps ?",
    "As-tu déjà eu un rapport anal ?",
    "As-tu déjà pratiqué le voyeurisme ?",
    "As-tu déjà eu un coup d'un soir ?",
    "As-tu déjà eu des relations sexuelles avec le.la partenaire d'un.e ami.e ?",
    "As-tu déjà été infidèle ?",
    "As-tu déjà eu des relations sexuelles que tu regrettes maintenant ?",
    "As-tu déjà eu des relations sexuelles en coup de vent ?",
    "As-tu déjà simulé l'orgasme ?",
    "As-tu déjà téléphoné ou répondu à un appel pendant un acte sexuel ?",
    "As-tu déjà eu des relations sexuelles avec plus de deux personnes dans la même semaine ?",
    "As-tu déjà acheté quelquechose dans un sex shop ?",
    "As-tu déjà eu des relations sexuelles dans un lieu public ?",
    "Ta situation affective"]
export const questionJaunes = [
    "Ta situation affective",
    "Ton romantisme",
    "Questionj 3",
    "Questionj 4"]
export const questionOrange = [
    "Mon occupation",
    "Mon odeur",
    "Ma couleur",
    "Mon auteur",
    "Mon métier",
    "Mon juron",
    "Mon chanteur.se/groupe de musique",
    "Mes prénoms",
    "Mon animal",
    "Ma réforme/évolution",
    "Mon secteur d'activité",
    "Ma fleur",
    "Mon plat",
    "Mon peintre",
    "Mon sport",
    "Mon héros.ïne de fiction",
    "Mon héros.ïne réel.le",
    "Mon oiseau",
    "Mon son/bruit",
    "Mon mot",
    "Ma boisson"]